#!/usr/bin/env python3
"""Regenerate src/components/site/vendored/manifest.ts.

Walks the three vendored families, pulls every exported component out of each
file, and emits the flat list /library/vendored renders. Run after re-syncing a
family; the output is what keeps the index honest about what exists.

    python3 scripts/gen-vendored.py
"""

import json
import pathlib
import re

DIRS = {
    "canvas": "src/components/facet/canvas",
    "backgrounds": "src/components/facet/bits/backgrounds",
    "animations": "src/components/facet/bits/animations",
    "components": "src/components/facet/bits/components",
}

# engine factories, capability probes and type-only names are not components
NOT_COMPONENT = re.compile(
    r"(create[A-Z]|supportsHtml|Instance$|Options$|Elements$|Props$|Config$|"
    r"Uniforms$|Ref$)"
)

HEADER = """/* GENERATED by scripts/gen-vendored.py — do not edit by hand.
 *
 * Every exported component from the three vendored families, flattened so
 * /library/vendored can mount them. The point is to find what crashes on a
 * bare render, which is the floor any real usage starts from.
 *
 * Each entry carries a LOADER, not a component reference. The eager-import
 * form this replaced pulled all 252 modules — and three.js, rapier3d and the
 * whole react-icons set behind them — into the route bundle whether or not a
 * tile ever scrolled into range. A loader defers the import() to the moment a
 * tile actually mounts, so the index ships its own shell first and a given
 * primitive arrives only when it is about to be shown. Measured: the route's
 * critical path went from 2557 KB to 240 KB gzipped.
 */"""


def main() -> None:
    entries: list[dict] = []
    imports: list[str] = []

    for family, directory in DIRS.items():
        for path in sorted(pathlib.Path(directory).glob("*.tsx")):
            src = path.read_text()

            named: list[str] = []
            for m in re.findall(
                r"^export (?:const|function|class)\s+([A-Z][A-Za-z0-9_]*)", src, re.M
            ):
                if m not in named:
                    named.append(m)

            # react-bits ships each component as `export default X`; canvas-ui
            # uses named exports. A default whose identifier is not also a named
            # export has to come in through the default import.
            default_name = None
            dm = re.search(
                r"export default (?:function\s+|const\s+)?([A-Z][A-Za-z0-9_]*)", src
            )
            if dm and dm.group(1) not in named:
                default_name = dm.group(1)

            targets = [(n, False) for n in named]
            if default_name:
                targets.append((default_name, True))

            keep = [(n, d) for n, d in targets if not NOT_COMPONENT.search(n)]
            if not keep:
                continue

            stem = path.stem
            alias_base = re.sub(r"[^a-z0-9]", "", stem).capitalize()
            # tsconfig maps "@/*" to "./src/*", so the leading "src/" has to
            # come off or the specifier resolves to "@/src/components/...".
            spec = f"@/{directory.removeprefix('src/')}/{stem}"

            for i, (name, is_default) in enumerate(keep):
                alias = f"P_{family}_{alias_base}_{i}"
                # A LOADER, not a static import. The eager form pulled all 252
                # modules — and three.js, rapier3d and react-icons behind them —
                # into the route bundle even for tiles that never scrolled into
                # range. Default exports are read off the namespace inside the
                # loader, which also sidesteps the fact that `import X as Y`
                # is not valid for a default binding.
                if is_default:
                    imports.append(
                        f'const {alias} = () =>\n'
                        f'  import("{spec}").then((m) => ({{ default: m.default }}));'
                    )
                else:
                    imports.append(
                        f'const {alias} = () =>\n'
                        f'  import("{spec}").then((m) => ({{ default: m.{name} }}));'
                    )
                entries.append(
                    {
                        "id": f"{family}/{stem}/{name}",
                        "family": family,
                        "alias": alias,
                    }
                )

    out = [HEADER, '"use client";', ""]
    out += imports
    out += ["", "export const PROBE_ENTRIES = ["]
    for e in entries:
        out.append(
            f'  {{ id: {json.dumps(e["id"])}, family: {json.dumps(e["family"])}, '
            f'load: {e["alias"]} }},'
        )
    out += ["] as const;", ""]

    target = pathlib.Path("src/components/site/vendored/manifest.ts")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(out))
    print(f"{len(entries)} components -> {target}")


if __name__ == "__main__":
    main()